services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: upsize-app

    ports:
      - "8000:8000"
      - "5173:5173"

    volumes:
      - .:/var/www

    env_file:
      - .env.docker

    depends_on:
      - mysql
      - notification-service

    networks:
      - upsize-network


  mysql:
    image: mysql:8.0

    container_name: upsize-mysql

    restart: always

    environment:
      MYSQL_DATABASE: upsize
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - upsize-network


  notification-service:
    build:
      context: ../UpSize-Notification-Service
      dockerfile: Dockerfile

    container_name: upsize-notification-service

    ports:
      - "8001:8001"

    networks:
      - upsize-network


volumes:
  mysql-data:


networks:
  upsize-network:
    driver: bridge