name: Laravel CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  laravel-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install npm dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Copy environment
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run Laravel tests
        env:
          MIDTRANS_SERVER_KEY: Mid-server-test
          MIDTRANS_CLIENT_KEY: Mid-client-test
          MIDTRANS_IS_PRODUCTION: false
        run: php artisan test